INSERT INTO book(name, author, publisher, price) VALUES ('Effective Java中文版(第2版)', '布洛克', '机械工业出版社', '41.10');
INSERT INTO book(name, author, publisher, price) VALUES ('Java编程思想', 'Bruce Eckel', '机械工业出版社', '86.40');
INSERT INTO book(name, author, publisher, price) VALUES ('Python基础教程', 'Magnus Lie Hetland', '人民邮电出版社', '78.20');
INSERT INTO book(name, author, publisher, price) VALUES ('Python 3网络爬虫开发实战', '崔庆才', '人民邮电出版社', '78.20');
INSERT INTO book(name, author, publisher, price) VALUES ('Spring实战', 'Craig Walls', '人民邮电出版社', '70.30');
INSERT INTO book(name, author, publisher, price) VALUES ('Spring微服务实战', 'John Carnell', '人民邮电出版社', '62.40');
INSERT INTO book(name, author, publisher, price) VALUES ('Spring Cloud微服务实战', '翟永超', '电子工业出版社', '70.30');
INSERT INTO book(name, author, publisher, price) VALUES ('Spring Boot实战', 'Craig Walls', '人民邮电出版社', '46.60');
INSERT INTO book(name, author, publisher, price) VALUES ('Docker实践', 'Ian Miell & Aidan H', '人民邮电出版社', '62.40');
INSERT INTO book(name, author, publisher, price) VALUES ('Kubernetes权威指南', '龚正等', '电子工业出版社', '94.00');
INSERT INTO book(name, author, publisher, price) VALUES ('Docker实战', 'Jeff Nickoloff', '电子工业出版社', '62.40');
INSERT INTO book(name, author, publisher, price) VALUES ('Go程序设计语言', '艾伦A. A. 多诺万', '机械工业出版社', '58.90');
INSERT INTO book(name, author, publisher, price) VALUES ('Go Web编程', 'Sau Sheong Chang', '人民邮电出版社', '62.40');
INSERT INTO book(name, author, publisher, price) VALUES ('Unity AR/VR开发', '王　寒　曾　坤　张义红', '机械工业出版社', '78.20');
INSERT INTO book(name, author, publisher, price) VALUES ('Swift编程权威指南 第2版', 'Matthew Mathias', '人民邮电出版社', '70.10');
INSERT INTO book(name, author, publisher, price) VALUES ('Kotlin实战', 'Dmitry Jemerov', '电子工业出版社', '70.30');
INSERT INTO book(name, author, publisher, price) VALUES ('JUnit实战', 'Petar Tahchiev', '人民邮电出版社', '62.40');
INSERT INTO book(name, author, publisher, price) VALUES ('实战Gradle', 'Benjamin Muschko', '电子工业出版社', '70.30');
INSERT INTO book(name, author, publisher, price) VALUES ('机器学习实战', '哈林顿', '人民邮电出版社', '54.50');
INSERT INTO book(name, author, publisher, price) VALUES ('实用机器学习', 'Henrik Brink', '机械工业出版社', '54.50');
INSERT INTO book(name, author, publisher, price) VALUES ('深度学习框架PyTorch快速开发与实战', '邢梦来 王硕 孙洋洋', '电子工业出版社', '69.00');
INSERT INTO book(name, author, publisher, price) VALUES ('面向对象的嵌入式软件开发 ', '周颖颖 李洋 钱瑛', '电子工业出版社', '88.00');
INSERT INTO book(name, author, publisher, price) VALUES ('Java9口袋指南（第4版）', 'Robert Liguori', '电子工业出版社', '49.00');
INSERT INTO book(name, author, publisher, price) VALUES ('Python与神经网络实战', '何宇健', '电子工业出版社', '79.00');
INSERT INTO book(name, author, publisher, price) VALUES ('Spring Boot 2企业应用实战', '疯狂软件', '电子工业出版社', '46.40');
INSERT INTO book(name, author, publisher, price) VALUES ('RxJava 2.x 实战', '沈哲', '电子工业出版社', '63.20');
INSERT INTO book(name, author, publisher, price) VALUES ('Java工程师修炼之道', '杭建', '电子工业出版社', '71.20');
INSERT INTO book(name, author, publisher, price) VALUES ('Qt高级编程', 'Mark Summerfield', '电子工业出版社', '55.20');